swagger: '2.0'
info:
  title: 'Criar Grupo de Recursos na Azure'
  description: 'Endpoint para criar um Grupo de Recursos na Azure.'
  version: '1.0'
consumes:
  - 'application/json'
produces:
  - 'application/json'
responses:
  200:
    description: 'Grupo de Recursos criado com sucesso.'
  500:
    description: 'Erro ao criar Grupo de Recursos.'
